### ISSUE TITLE
When searching, pressing return should insert item

### ISSUE THREAD

**Issue by rjmunro** [simoncozens/songbee#2]

**Comment by simoncozens** [comment]
losed by 55de485b6479de6991b3f2bd301bb673457fa137: When searching, pressing return should insert item

**Comment by simoncozens** [comment]
Fixed in SHA: 55de485b6479de6991b3f2bd301bb673457fa137

**Comment by rjmunro** [comment]
It's only fixed in editing playlists, not searching for a song in go mode AFAICS.
